"""add is_active column to users

Revision ID: 60d50eac2025
Revises: merge_heads_final
Create Date: 2025-05-06 14:29:53.849181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '60d50eac2025'
down_revision: Union[str, None] = 'merge_heads_final'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_monday_configs_id', table_name='monday_configs')
    # op.drop_table('monday_configs')
    # op.drop_index('ix_monday_connections_id', table_name='monday_connections')
    # op.drop_table('monday_connections')
    # op.drop_index('ix_social_links_id', table_name='social_links')
    # op.drop_index('ix_social_links_url', table_name='social_links')
    # op.drop_table('social_links')
    # op.drop_index('ix_links_id', table_name='links')
    # op.drop_table('links')
    # op.drop_index('ix_link_metrics_id', table_name='link_metrics')
    # op.drop_table('link_metrics')
    # op.drop_index('ix_companies_id', table_name='companies')
    # op.drop_table('companies')
    # op.drop_index('ix_users_email', table_name='users')
    # op.drop_index('ix_users_id', table_name='users')
    # op.drop_index('ix_users_username', table_name='users')
    # op.drop_table('users')
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
