/**
 * Shared error codes used across backend and frontend.
 */

const ERROR_CODES = {
    // Auth
    UNAUTHORIZED: 'UNAUTHORIZED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',

    // Validation
    INVALID_URL: 'INVALID_URL',
    PLATFORM_NOT_SUPPORTED: 'PLATFORM_NOT_SUPPORTED',
    MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',

    // Resources
    COMPANY_NOT_FOUND: 'COMPANY_NOT_FOUND',
    LINK_NOT_FOUND: 'LINK_NOT_FOUND',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // Monday.com
    MONDAY_CONNECTION_FAILED: 'MONDAY_CONNECTION_FAILED',
    MONDAY_SYNC_FAILED: 'MONDAY_SYNC_FAILED',

    // General
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    RATE_LIMITED: 'RATE_LIMITED',
};

module.exports = { ERROR_CODES };
